//! Topic detection (P6) — F40.
//!
//! Community detection on the Entity co-occurrence graph.  Two
//! entities are linked when they appear together in the same Message,
//! Chunk, Episode, Action, or Artifact (via `MENTIONS`).  Communities
//! of size ≥ 2 become Topic nodes; member entities are linked by
//! `BELONGS_TO`.
//!
//! Algorithm: weighted Label Propagation (LPA).  Each entity starts
//! in its own community; iteratively, every entity adopts the
//! highest-weighted community label among its neighbours, with ties
//! broken by the smaller label id for deterministic convergence.
//! Linear time per iteration; converges in 5–10 sweeps for graphs
//! up to ~10K entities — comfortably within the periodic worker
//! budget in spec Part VI.
//!
//! Louvain is available via `CALL uni.algo.louvain(...)` in uni-db
//! for very large graphs.  We keep LPA as the default because it
//! avoids materialising a graph projection and is dead simple to
//! reason about; swap in Louvain when the entity count grows past
//! ~50K.

// Rust guideline compliant

use std::collections::HashMap;

use serde::Serialize;
use uni_db::Value;
use uniko_store::schema::{edges, labels};
use uniko_store::types::datetime_value;
use uniko_store::{KnowledgeBase, NodeId, UnikoError};

/// Configuration for the topic detection pass.
#[derive(Debug, Clone, Copy)]
pub struct TopicConfig {
    /// Minimum members for a community to become a Topic.  Singletons
    /// are always skipped because they carry no aggregation value.
    pub min_community_size: usize,
    /// Maximum LPA iterations before convergence is forced.
    pub max_iterations: usize,
    /// Hard cap on the number of co-occurrence pairs pulled for
    /// projection.  Caps memory + Cypher latency on dense graphs.
    pub max_pairs: i64,
}

impl Default for TopicConfig {
    fn default() -> Self {
        Self {
            min_community_size: 2,
            max_iterations: 10,
            max_pairs: 100_000,
        }
    }
}

/// Outcome of one [`detect_topics_once`] call.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TopicReport {
    /// New Topic nodes created.
    pub created: usize,
    /// Existing Topic nodes whose membership was refreshed.
    pub updated: usize,
    /// Total entities assigned to a Topic.
    pub entities_assigned: usize,
}

/// Run a topic-detection pass and persist the resulting Topic nodes.
///
/// Communities are detected by weighted LPA on the co-occurrence
/// graph.  Each surviving community (≥ `cfg.min_community_size`)
/// becomes a Topic with a deterministic id derived from its sorted
/// member set, so re-runs are idempotent.
///
/// Equivalent to [`detect_topics_once_with_llm`] with `llm_alias =
/// None`; topic names fall back to the deterministic member-name
/// join.
///
/// # Errors
///
/// Returns [`UnikoError::Storage`] when projection queries or graph
/// writes fail.
pub async fn detect_topics_once(
    kb: &KnowledgeBase,
    cfg: TopicConfig,
) -> Result<TopicReport, UnikoError> {
    detect_topics_once_with_llm(kb, cfg, None).await
}

/// Run a topic-detection pass with an optional LLM alias for
/// community naming.
///
/// When `llm_alias` is `Some(_)` and the crate is built with the
/// `llm` feature, the topic name is generated by a single LLM call
/// per community.  On feature-off, on `None`, or on LLM failure,
/// names fall back transparently to the deterministic
/// member-name join — names are cosmetic per spec §6 and must
/// never block a sweep.
///
/// # Errors
///
/// Returns [`UnikoError::Storage`] when projection queries or graph
/// writes fail.  LLM naming failures are swallowed.
pub async fn detect_topics_once_with_llm(
    kb: &KnowledgeBase,
    cfg: TopicConfig,
    llm_alias: Option<&str>,
) -> Result<TopicReport, UnikoError> {
    let entities = fetch_entities(kb).await?;
    if entities.is_empty() {
        return Ok(TopicReport::default());
    }

    let id_to_idx: HashMap<NodeId, usize> = entities
        .iter()
        .enumerate()
        .map(|(i, e)| (e.node_id, i))
        .collect();

    let pairs = fetch_cooccurrence_pairs(kb, cfg.max_pairs).await?;
    let mut adj: Vec<Vec<(usize, f64)>> = vec![Vec::new(); entities.len()];
    for CoPair { a, b, weight } in &pairs {
        let (Some(&ia), Some(&ib)) = (id_to_idx.get(a), id_to_idx.get(b)) else {
            continue;
        };
        if ia == ib {
            continue;
        }
        adj[ia].push((ib, *weight));
        adj[ib].push((ia, *weight));
    }

    let labels_out = run_lpa(&adj, cfg.max_iterations);
    let communities = group_by_label(&labels_out, &entities);

    let mut report = TopicReport::default();
    for community in communities.values() {
        if community.len() < cfg.min_community_size {
            continue;
        }
        let topic_id = stable_topic_id(community);
        let outcome = upsert_topic(kb, &topic_id, community, llm_alias).await?;
        if outcome.created {
            report.created += 1;
        } else {
            report.updated += 1;
        }
        report.entities_assigned += community.len();
    }
    Ok(report)
}

// ── Helpers ────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct EntityRow {
    node_id: NodeId,
    entity_id: String,
    name: String,
    /// Kniv-assigned NER type (e.g. `"PERSON"`, `"ORG"`, `"LOC"`).
    /// Empty when ingest used rule-based fallback only.  Used by
    /// [`community_summary`] to group members by type so the
    /// summary reads like "Topic of 5 entities (3 PERSON, 2 ORG)"
    /// instead of a flat name list.
    entity_type: String,
    embedding: Option<Vec<f32>>,
}

struct CoPair {
    a: NodeId,
    b: NodeId,
    weight: f64,
}

async fn fetch_entities(kb: &KnowledgeBase) -> Result<Vec<EntityRow>, UnikoError> {
    let session = kb.db().session();
    let cypher = "MATCH (e:Entity) \
                  RETURN id(e) AS nid, e.entity_id AS eid, e.name AS name, \
                         coalesce(e.entity_type, '') AS etype, \
                         e.embedding AS emb";
    let result = session
        .query_with(cypher)
        .fetch_all()
        .await
        .map_err(|e| UnikoError::Storage(e.to_string()))?;

    let mut out = Vec::new();
    for row in result.rows() {
        let Ok(nid) = row.get::<i64>("nid") else {
            continue;
        };
        let eid: String = row.get("eid").unwrap_or_default();
        let name: String = row.get("name").unwrap_or_default();
        let entity_type: String = row.get("etype").unwrap_or_default();
        let embedding: Option<Vec<f32>> = row.get::<Vec<f32>>("emb").ok();
        out.push(EntityRow {
            node_id: nid,
            entity_id: eid,
            name,
            entity_type,
            embedding,
        });
    }
    Ok(out)
}

/// Aggregate co-occurrence across MENTIONS-source labels (Message,
/// Chunk, Episode, Action, Artifact).  Returns ordered pairs (a < b)
/// to dedupe the undirected co-occurrence relation.
async fn fetch_cooccurrence_pairs(
    kb: &KnowledgeBase,
    max_pairs: i64,
) -> Result<Vec<CoPair>, UnikoError> {
    let session = kb.db().session();
    let cypher = "MATCH (src)-[:MENTIONS]->(a:Entity) \
                  MATCH (src)-[:MENTIONS]->(b:Entity) \
                  WHERE id(a) < id(b) \
                  WITH id(a) AS a, id(b) AS b, count(*) AS w \
                  RETURN a, b, w \
                  ORDER BY w DESC \
                  LIMIT $lim";
    let result = session
        .query_with(cypher)
        .param("lim", max_pairs)
        .fetch_all()
        .await
        .map_err(|e| UnikoError::Storage(e.to_string()))?;

    let mut out = Vec::new();
    for row in result.rows() {
        let Ok(a) = row.get::<i64>("a") else { continue };
        let Ok(b) = row.get::<i64>("b") else { continue };
        let w: i64 = row.get("w").unwrap_or(1);
        out.push(CoPair {
            a,
            b,
            weight: w as f64,
        });
    }
    Ok(out)
}

/// Weighted LPA.  Each entity adopts the label most heavily weighted
/// among its neighbours.  Ties broken by smaller label id for
/// stable convergence.
fn run_lpa(adj: &[Vec<(usize, f64)>], max_iter: usize) -> Vec<u32> {
    let n = adj.len();
    if n == 0 {
        return Vec::new();
    }
    let mut labels: Vec<u32> = (0..n as u32).collect();

    for _iter in 0..max_iter {
        let mut changed = false;
        for v in 0..n {
            if adj[v].is_empty() {
                continue;
            }
            let mut tally: HashMap<u32, f64> = HashMap::new();
            for &(u, w) in &adj[v] {
                *tally.entry(labels[u]).or_insert(0.0) += w;
            }
            let mut best_label = labels[v];
            let mut best_weight = f64::NEG_INFINITY;
            for (lbl, w) in &tally {
                if *w > best_weight || ((*w - best_weight).abs() < 1e-12 && *lbl < best_label) {
                    best_weight = *w;
                    best_label = *lbl;
                }
            }
            if best_label != labels[v] {
                labels[v] = best_label;
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    labels
}

fn group_by_label(labels_out: &[u32], entities: &[EntityRow]) -> HashMap<u32, Vec<EntityRow>> {
    let mut groups: HashMap<u32, Vec<EntityRow>> = HashMap::new();
    for (i, &lbl) in labels_out.iter().enumerate() {
        groups.entry(lbl).or_default().push(entities[i].clone());
    }
    groups
}

/// Deterministic Topic id derived from the sorted member entity_ids.
fn stable_topic_id(community: &[EntityRow]) -> String {
    let mut ids: Vec<&str> = community.iter().map(|e| e.entity_id.as_str()).collect();
    ids.sort_unstable();
    let mut buf = String::new();
    for id in ids {
        buf.push_str(id);
        buf.push('|');
    }
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    buf.hash(&mut h);
    format!("topic_{:016x}", h.finish())
}

struct UpsertOutcome {
    created: bool,
}

async fn upsert_topic(
    kb: &KnowledgeBase,
    topic_id: &str,
    members: &[EntityRow],
    llm_alias: Option<&str>,
) -> Result<UpsertOutcome, UnikoError> {
    let existing = kb
        .get_node_by_ext_id(labels::TOPIC, "topic_id", topic_id)
        .await?
        .is_some();

    let name = resolve_topic_name(kb, members, llm_alias).await;
    let summary = community_summary(members);
    let entity_count = members.len() as i64;
    let pooled = pool_embedding(members);

    let mut props = HashMap::new();
    props.insert("name".into(), Value::String(name));
    props.insert("summary".into(), Value::String(summary));
    props.insert("entity_count".into(), Value::Int(entity_count));
    if let Some(vec) = pooled {
        props.insert("embedding".into(), Value::Vector(vec));
    }
    if !existing {
        props.insert("created_at".into(), datetime_value(chrono::Utc::now()));
    }

    let topic_node = kb
        .merge_node(labels::TOPIC, "topic_id", topic_id, &props)
        .await?;

    for member in members {
        let res = kb
            .create_edge(
                edges::BELONGS_TO,
                member.node_id,
                topic_node,
                &HashMap::new(),
            )
            .await;
        if let Err(UnikoError::Storage(msg)) = &res
            && (msg.contains("duplicate") || msg.contains("already"))
        {
            continue;
        }
        res?;
    }

    Ok(UpsertOutcome { created: !existing })
}

/// Resolve a topic name, preferring an LLM-generated name when the
/// `llm` feature is enabled and an alias is configured, otherwise
/// falling back to the deterministic [`community_name`].
///
/// LLM failures (network, empty response, missing alias) fall back
/// silently — topic names are cosmetic and must not block a sweep.
async fn resolve_topic_name(
    kb: &KnowledgeBase,
    members: &[EntityRow],
    llm_alias: Option<&str>,
) -> String {
    #[cfg(feature = "llm")]
    if let Some(alias) = llm_alias
        && let Some(name) = community_name_llm(kb, members, alias).await
    {
        return name;
    }
    #[cfg(not(feature = "llm"))]
    {
        let _ = kb;
        let _ = llm_alias;
    }
    community_name(members)
}

/// LLM-generated topic name.  Single attempt, no retry — cosmetic
/// only.  Returns `None` on any failure so the caller can fall back.
#[cfg(feature = "llm")]
async fn community_name_llm(
    kb: &KnowledgeBase,
    members: &[EntityRow],
    llm_alias: &str,
) -> Option<String> {
    use uni_db::xervo::{GenerationOptions, Message};

    let mut bucket: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
    for m in members {
        if !m.entity_type.is_empty() {
            *bucket.entry(m.entity_type.as_str()).or_insert(0) += 1;
        }
    }
    let types = if bucket.is_empty() {
        "untyped".to_string()
    } else {
        bucket
            .iter()
            .map(|(t, n)| format!("{n} {t}"))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let mut names: Vec<&str> = members.iter().map(|e| e.name.as_str()).collect();
    names.sort_unstable();
    let sample: Vec<&str> = names.into_iter().take(8).collect();

    let prompt = format!(
        "Given {} entities ({}), representative members: {}.\n\
         Propose a short topic name (at most 4 words). Output only the name.",
        members.len(),
        types,
        sample.join(", "),
    );

    let messages = vec![Message::user(&prompt)];
    let options = GenerationOptions {
        max_tokens: Some(64),
        ..Default::default()
    };

    let res = kb
        .db()
        .xervo()
        .generate(llm_alias, &messages, options)
        .await
        .ok()?;

    let trimmed = res.text.trim();
    if trimmed.is_empty() {
        return None;
    }
    // Strip wrapping quotes / Markdown emphasis if the model added any.
    let cleaned =
        trimmed.trim_matches(|c: char| c == '"' || c == '\'' || c == '`' || c == '*' || c == '_');
    if cleaned.is_empty() {
        None
    } else {
        Some(cleaned.to_string())
    }
}

/// MVP topic naming fallback: join up to three member entity names.
fn community_name(members: &[EntityRow]) -> String {
    let mut names: Vec<&str> = members.iter().map(|e| e.name.as_str()).collect();
    names.sort_unstable();
    let top: Vec<&str> = names.into_iter().take(3).collect();
    if top.is_empty() {
        "topic".into()
    } else {
        top.join(", ")
    }
}

/// Build a one-line summary that buckets members by their Kniv
/// `entity_type`.  When no type information is available (e.g. ingest
/// ran in rule-only mode) the summary falls back to the flat name
/// list from [`community_name`].
fn community_summary(members: &[EntityRow]) -> String {
    let mut by_type: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
    for m in members {
        if !m.entity_type.is_empty() {
            *by_type.entry(m.entity_type.as_str()).or_insert(0) += 1;
        }
    }
    if by_type.is_empty() {
        return format!(
            "Topic of {} entities; representative members: {}",
            members.len(),
            community_name(members)
        );
    }
    let breakdown: Vec<String> = by_type.iter().map(|(t, n)| format!("{n} {t}")).collect();
    format!(
        "Topic of {} entities ({}); representative members: {}",
        members.len(),
        breakdown.join(", "),
        community_name(members)
    )
}

/// Mean-pool member embeddings.  Returns None when no member has an
/// embedding — Topic.embedding stays nullable so search just skips it.
fn pool_embedding(members: &[EntityRow]) -> Option<Vec<f32>> {
    let mut iter = members.iter().filter_map(|e| e.embedding.as_ref());
    let first = iter.next()?;
    let dim = first.len();
    let mut sum = first.clone();
    let mut count = 1_usize;
    for vec in iter {
        if vec.len() != dim {
            continue;
        }
        for (s, v) in sum.iter_mut().zip(vec.iter()) {
            *s += *v;
        }
        count += 1;
    }
    let n = count as f32;
    for s in sum.iter_mut() {
        *s /= n;
    }
    Some(sum)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lpa_isolated_nodes_keep_own_labels() {
        let adj = vec![vec![], vec![], vec![]];
        let labels_out = run_lpa(&adj, 10);
        let mut s: Vec<u32> = labels_out.clone();
        s.sort_unstable();
        s.dedup();
        assert_eq!(s.len(), 3);
    }

    #[test]
    fn lpa_clique_collapses_to_one_label() {
        let edge = |i: usize, n: usize| (0..n).filter(|&j| j != i).map(|j| (j, 1.0)).collect();
        let adj: Vec<Vec<(usize, f64)>> = (0..4).map(|i| edge(i, 4)).collect();
        let labels_out = run_lpa(&adj, 10);
        let first = labels_out[0];
        assert!(labels_out.iter().all(|&l| l == first));
    }

    #[test]
    fn lpa_two_cliques_one_thin_edge() {
        let n = 6;
        let mut adj: Vec<Vec<(usize, f64)>> = vec![Vec::new(); n];
        for i in 0..3 {
            for j in 0..3 {
                if i != j {
                    adj[i].push((j, 5.0));
                }
            }
        }
        for i in 3..6 {
            for j in 3..6 {
                if i != j {
                    adj[i].push((j, 5.0));
                }
            }
        }
        adj[2].push((3, 1.0));
        adj[3].push((2, 1.0));

        let labels_out = run_lpa(&adj, 20);
        assert_eq!(labels_out[0], labels_out[1]);
        assert_eq!(labels_out[1], labels_out[2]);
        assert_eq!(labels_out[3], labels_out[4]);
        assert_eq!(labels_out[4], labels_out[5]);
        assert_ne!(labels_out[0], labels_out[3]);
    }

    fn ent(eid: &str, name: &str) -> EntityRow {
        EntityRow {
            node_id: 0,
            entity_id: eid.into(),
            name: name.into(),
            entity_type: String::new(),
            embedding: None,
        }
    }

    fn ent_with_type(eid: &str, name: &str, etype: &str) -> EntityRow {
        EntityRow {
            node_id: 0,
            entity_id: eid.into(),
            name: name.into(),
            entity_type: etype.into(),
            embedding: None,
        }
    }

    #[test]
    fn stable_topic_id_is_membership_invariant() {
        let a = stable_topic_id(&[ent("e1", "x"), ent("e2", "y")]);
        let b = stable_topic_id(&[ent("e2", "y"), ent("e1", "x")]);
        let c = stable_topic_id(&[ent("e1", "x"), ent("e3", "z")]);
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn community_name_joins_up_to_three() {
        let n = community_name(&[
            ent("e1", "a"),
            ent("e2", "b"),
            ent("e3", "c"),
            ent("e4", "d"),
        ]);
        assert_eq!(n, "a, b, c");
    }

    #[test]
    fn pool_embedding_averages() {
        let mut e1 = ent("e1", "x");
        e1.embedding = Some(vec![1.0, 2.0, 3.0]);
        let mut e2 = ent("e2", "y");
        e2.embedding = Some(vec![3.0, 2.0, 1.0]);
        let pooled = pool_embedding(&[e1, e2]).expect("pooled");
        assert_eq!(pooled, vec![2.0, 2.0, 2.0]);
    }

    #[test]
    fn pool_embedding_none_when_no_member_has_one() {
        let pooled = pool_embedding(&[ent("e1", "x"), ent("e2", "y")]);
        assert!(pooled.is_none());
    }

    #[test]
    fn community_summary_buckets_by_kniv_entity_type() {
        // 3 PERSONs + 2 ORGs, alphabetical bucket order in the
        // breakdown (BTreeMap-backed).
        let members = vec![
            ent_with_type("e1", "alice", "PERSON"),
            ent_with_type("e2", "bob", "PERSON"),
            ent_with_type("e3", "carol", "PERSON"),
            ent_with_type("e4", "acme", "ORG"),
            ent_with_type("e5", "globex", "ORG"),
        ];
        let s = community_summary(&members);
        assert!(s.contains("2 ORG"), "summary = {s}");
        assert!(s.contains("3 PERSON"), "summary = {s}");
    }

    #[test]
    fn community_summary_falls_back_when_no_types() {
        let members = vec![ent("e1", "x"), ent("e2", "y")];
        let s = community_summary(&members);
        assert!(!s.contains('('), "expected no bucket parens, got {s}");
        assert!(s.contains("representative members"));
    }
}
