#!/usr/bin/env python3
"""Generate a PEP 503 "simple" package index from this repo's GitHub releases.

uniko's Python wheels are distributed as GitHub *release assets* (each is
~120 MB, over PyPI's 100 MB per-file limit), so they cannot live on PyPI. This
script builds a static simple-repository index whose per-project pages link
directly at those release-asset download URLs. Published on the docs GitHub
Pages site, it lets `pip`/`poetry` install the wheels via, e.g.:

    pip install uniko --extra-index-url https://rustic-ai.github.io/uniko/packages/

The index is regenerated on every docs deploy (see
`.github/workflows/deploy-docs.yml`), so new releases appear automatically.

Each release ships several distinct distributions (`uniko`, `uniko-cuda`,
`uniko-metal`); every wheel/sdist is grouped under its normalized project name,
which is the correct PEP 503 layout (one project per page). Asset digests from
the GitHub API are used to pin `#sha256=` fragments — no wheels are downloaded.

Environment:
  GITHUB_REPOSITORY  owner/repo to read releases from (default rustic-ai/uniko)
  GITHUB_TOKEN       optional; raises the API rate limit and reads private repos
  PACKAGE_INDEX_DIR  output directory (default website/docs/packages)
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request

REPO = os.environ.get("GITHUB_REPOSITORY", "rustic-ai/uniko")
OUT = os.environ.get("PACKAGE_INDEX_DIR", "website/docs/packages")
TOKEN = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")

# The project floor: abi3 wheels are built for cp310, and the crate requires
# Python >= 3.10. Wheel platform tags already encode this, but advertising it at
# the index level also constrains the sdist fallback. Bump if the floor changes.
REQUIRES_PYTHON = ">=3.10"

_HEAD = (
    "<!DOCTYPE html>\n<html>\n  <head>\n"
    '    <meta name="pypi:repository-version" content="1.0">\n'
    "  </head>\n  <body>\n"
)
_FOOT = "  </body>\n</html>\n"


def normalize(name: str) -> str:
    """PEP 503 name normalization."""
    return re.sub(r"[-_.]+", "-", name).lower()


def dist_name(filename: str) -> str | None:
    """Distribution name from a wheel or sdist filename."""
    if filename.endswith(".whl"):
        return filename.split("-")[0]
    if filename.endswith(".tar.gz"):
        return filename[: -len(".tar.gz")].rsplit("-", 1)[0]
    return None


def fetch_releases() -> list:
    """All (non-draft) releases for the repo, following pagination."""
    releases = []
    page = 1
    while True:
        url = f"https://api.github.com/repos/{REPO}/releases?per_page=100&page={page}"
        headers = {"Accept": "application/vnd.github+json", "User-Agent": "uniko-index-gen"}
        if TOKEN:
            headers["Authorization"] = f"Bearer {TOKEN}"
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req) as resp:
                batch = json.load(resp)
        except urllib.error.HTTPError as e:
            sys.exit(f"error: GitHub API returned {e.code} for {url}: {e.read().decode(errors='replace')}")
        if not batch:
            break
        releases.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return releases


def collect(releases: list) -> dict:
    """Map normalized project name -> sorted list of (filename, url, sha256)."""
    projects: dict = {}
    for rel in releases:
        if rel.get("draft"):
            continue
        for asset in rel.get("assets", []):
            fn = asset["name"]
            if not (fn.endswith(".whl") or fn.endswith(".tar.gz")):
                continue
            proj = normalize(dist_name(fn))
            digest = asset.get("digest") or ""
            sha = digest.split(":", 1)[1] if digest.startswith("sha256:") else None
            projects.setdefault(proj, []).append((fn, asset["browser_download_url"], sha))
    for files in projects.values():
        files.sort()
    return projects


def write(path: str, body: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)


def main() -> None:
    projects = collect(fetch_releases())

    # Root index: one link per project.
    lines = [_HEAD, "    <!-- Generated by scripts/ci/gen_package_index.py — do not edit by hand. -->\n"]
    for proj in sorted(projects):
        lines.append(f'    <a href="{proj}/">{proj}</a>\n')
    lines.append(_FOOT)
    write(os.path.join(OUT, "index.html"), "".join(lines))

    # Per-project pages.
    for proj, files in sorted(projects.items()):
        lines = [
            _HEAD,
            f"    <!-- Generated by scripts/ci/gen_package_index.py — do not edit by hand.\n"
            f"         Files are GitHub release assets for '{proj}'. -->\n",
        ]
        for fn, url, sha in files:
            frag = f"#sha256={sha}" if sha else ""
            rp = f' data-requires-python="{REQUIRES_PYTHON.replace(">", "&gt;").replace("<", "&lt;")}"'
            lines.append(f'    <a href="{url}{frag}"{rp}>{fn}</a>\n')
        lines.append(_FOOT)
        write(os.path.join(OUT, proj, "index.html"), "".join(lines))

    summary = ", ".join(f"{p} ({len(v)})" for p, v in sorted(projects.items())) or "(none)"
    print(f"wrote package index to {OUT}: {summary}")


if __name__ == "__main__":
    main()
